{
  lib,
  config,
  inputs,
  hostMeta,
  hostName,
  hostBaseHome,
  isLinux,
  isDarwin,
  ...
}:

let
  inherit (lib) mkDefault mkEnableOption mkIf mkMerge mkOption types;

  homeManagerModule =
    if isDarwin then
      inputs.home-manager.darwinModules.home-manager
    else
      inputs.home-manager.nixosModules.home-manager;

  userOptions =
    { name, ... }:
    {
      options = {
        name = mkOption {
          type = types.str;
          default = name;
          example = "lh";
          description = "User name for this host.";
        };

        authorizedKeys = mkOption {
          type = types.listOf types.str;
          default = [ ];
          description = "SSH public keys for the user.";
        };

        homeConfiguration = mkOption {
          type = types.nullOr types.path;
          default = null;
          example = "./home.nix";
          description = "Path to the Home Manager configuration for this user.";
        };
      };
    };
in
{
  imports = [
    homeManagerModule
  ];

  options = {
    custom.system.stacks.base.user.enable = mkEnableOption "Enable user management.";

    custom.system.users = mkOption {
      type = types.attrsOf (types.submodule userOptions);
      default = { };
      description = "User definitions for this host.";
    };

    custom.system.host.primaryUser = mkOption {
      type = types.nullOr types.str;
      default = null;
      description = "Primary user for this host.";
    };

    hostSpec.users = mkOption {
      type = types.attrsOf (types.submodule userOptions);
      default = { };
      description = "Host-specific user options.";
    };

    hostSpec.primaryUser = mkOption {
      type = types.nullOr types.str;
      default = null;
      description = "The primary user on this system. Used for setting the login user in NixOS-WSL.";
    };
  };

  config = lib.mkIf config.custom.system.stacks.base.user.enable (lib.mkMerge [
    {
      hostSpec.users = mkDefault config.custom.system.users;
      hostSpec.primaryUser = mkDefault config.custom.system.host.primaryUser;

      home-manager = {
        useUserPackages = true;
        extraSpecialArgs = {
          inherit inputs;
          inherit hostBaseHome;
          inherit isLinux;
          inherit isDarwin;
          customLib = lib.custom;
          inherit hostMeta;
          inherit hostName;
        };
      };
    }

    (lib.optionalAttrs isLinux {
      users = {
        mutableUsers = false;
        # Generated by `mkpasswd`
        users.root.initialHashedPassword = lib.mkDefault "$y$j9T$k3PWrdywWLH7PwDusAq2i.$eSsxc34TvdW1j0J7DjQnqtaTMvgFxVFYlVsBYdffnlA";
      };

      environment.pathsToLink = [
        "/share/applications"
        "/share/xdg-desktop-portal"
      ];
    })

    {
      users = lib.mkMerge (
        map (cfg: {
          groups.${cfg.name} = { };
          users.${cfg.name} = {
            home = lib.mkDefault (if isDarwin then "/Users/${cfg.name}" else "/home/${cfg.name}");
            openssh.authorizedKeys.keys = cfg.authorizedKeys;
          }
          // lib.optionalAttrs isLinux {
            isNormalUser = true;
            group = cfg.name;
            extraGroups = [
              "wheel"
              "users"
            ];
            initialPassword = cfg.name;
          };
        }) (builtins.attrValues config.hostSpec.users)
      );
      home-manager.users = lib.mkMerge (
        map (
          cfg:
          lib.mkIf (cfg.homeConfiguration != null) {
            ${cfg.name} = {
              imports = [
                hostBaseHome
                (lib.custom.fromFlakeRoot "home")
                cfg.homeConfiguration
              ];
            };
          }
        ) (builtins.attrValues config.hostSpec.users)
      );
    }
  ]);
}
